services:
  pixman:
    image: pixman/pixman
    restart: always
    container_name: pixman
    environment:
      - http_proxy=http://192.168.50.50:7890
      - https_proxy=http://192.168.50.50:7890
      - MYTVSUPER_TOKEN=YOUR_TOKEN
      - HAMI_SESSION_ID=pixman-e8fb92ba4a350a4334088c8360258da2
      - HAMI_SERIAL_NO=5645746888
      - HAMI_SESSION_IP=114.514.191.981
    ports:
      - 5050:5000
